# Compose file for backend for janusgraph.
# docker-compose --file docker-compose-janus.yml --project-name janus
version: '3.3'
services:
  janusgraphsvc:
    image: janusgraph:latest
    ports:
      - 8192
    volumes:
      - type: bind
        source: ./conf
        target: /app/conf
    networks:
      - default-network
    entrypoint: 
      - bin/gremlin-server.sh
      - conf/gremlin-server/gremlin-server-docker-test.yaml

  cassandrasvc:
    image: cassandra:latest
    # ports:
    #   - "7000"
    #   - "7001"
    #   - "7199"
    #   - "9042"
    #   - "9160"
    networks:
      - default-network

  elasticsearchsvc:
    image: elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    # ports:
    #   - "9200:9200"
    #   - "9300:9300"
    environment: 
      - discovery.type=single-node
    volumes:
      - type: volume
        source: elasticsearchdata
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: false
    networks:
      - default-network

volumes:
  elasticsearchdata:

networks: 
  default-network:
