# Compose file for backend for janusgraph.
# docker-compose --file docker-compose-janus.yml --project-name janus
version: '3.3'
services:
  janusgraphclient:
    image: janusgraph:0.2.0
    # ports:
    #   - "8192:8192"
    volumes:
      - type: bind
        source: ./conf-client
        target: /app/conf
    networks:
      - default-network
    entrypoint: "sleep 5h"
    
  janusgraphsvc:
    image: janusgraph:0.2.0
    ports:
      - "8192:8192"
    volumes:
      - type: bind
        source: ./conf
        target: /app/conf
    networks:
      - default-network
    entrypoint: 
      - bin/gremlin-server.sh
    command: conf/gremlin-server/test-gremlin-server-test.yaml

  cassandrasvc:
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment: 
      - CASSANDRA_START_RPC=true
    networks:
      - default-network

  elasticsearchsvc:
    image: elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment: 
      - discovery.type=single-node
    volumes:
      - type: volume
        source: elasticsearchdata
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: false
    networks:
      - default-network

volumes:
  elasticsearchdata:

networks: 
  default-network:
