apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic
  name: elastic
spec:
  clusterIP: None
  ports:
  - name: rest
    port: 9200
    targetPort: rest
  - name: nodes
    port: 9300
    targetPort: nodes
  selector:
    app: elastic