apiVersion: v1
kind: kind: Service
metadata:
  name:  cassandra
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  serviceName: "cassandra"
  type:  LoadBalancer
  # Add all cassandra ports.
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080
---
apiVersion: v1
kind: StatefulSet
metadata:
  name: "cassandra-cluster"
spec:
  selector:
    matchLabels:
      app: cassandra
